### ISSUE TITLE
Update s3 credentials for the files endpoint in staging

### ISSUE THREAD

**Issue by wgwz** [regen-network/registry-server#305]
Currently, the staging environment returns a 500 error when using the files endpoint:

```
2023-03-21T14:30:04.790767+00:00 heroku[router]: at=info method=POST path="/files" host=api-staging.registry.regen.network request_id=effad66a-187e-41
f3-a464-cec481822e88 fwd="90.126.106.114" dyno=web.1 connect=0ms service=101ms status=500 bytes=532 protocol=https
2023-03-21T14:30:03.135326+00:00 heroku[web.1]: Process running mem=1056M(102.8%)                                                                     
2023-03-21T14:30:03.137252+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)                                                                     
2023-03-21T14:30:04.790378+00:00 app[web.1]: registry-server: s3 Error AccessDenied: Access Denied                                                    
2023-03-21T14:30:04.790415+00:00 app[web.1]: registry-server:     at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:710:35)       
2023-03-21T14:30:04.790451+00:00 app[web.1]: registry-server:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:2
0)
2023-03-21T14:30:04.790473+00:00 app[web.1]: registry-server:     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2023-03-21T14:30:04.790493+00:00 app[web.1]: registry-server:     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)
2023-03-21T14:30:04.790510+00:00 app[web.1]: registry-server:     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
2023-03-21T14:30:04.790530+00:00 app[web.1]: registry-server:     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
2023-03-21T14:30:04.790550+00:00 app[web.1]: registry-server:     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
2023-03-21T14:30:04.790569+00:00 app[web.1]: registry-server:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
2023-03-21T14:30:04.790597+00:00 app[web.1]: registry-server:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:688:12)
2023-03-21T14:30:04.790610+00:00 app[web.1]: registry-server:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:1
8) {
2023-03-21T14:30:04.790643+00:00 app[web.1]: registry-server:   code: 'AccessDenied',
2023-03-21T14:30:04.790660+00:00 app[web.1]: registry-server:   region: null,
2023-03-21T14:30:04.790684+00:00 app[web.1]: registry-server:   time: 2023-03-21T14:30:04.782Z,
2023-03-21T14:30:04.790703+00:00 app[web.1]: registry-server:   requestId: '804GGBMQYD7H9DQN',
2023-03-21T14:30:04.790723+00:00 app[web.1]: registry-server:   extendedRequestId: 'w0Z8CdFV4xMmkd+Q95rsgIGLW9h5zpm8eQn2rVgX/+yPJEMA9/UEsHWtLQYkYr4ZPP
6Xl/pbzUo=',
2023-03-21T14:30:04.790741+00:00 app[web.1]: registry-server:   cfId: undefined,
2023-03-21T14:30:04.790767+00:00 app[web.1]: registry-server:   statusCode: 403,
2023-03-21T14:30:04.790779+00:00 app[web.1]: registry-server:   retryable: false,
2023-03-21T14:30:04.790811+00:00 app[web.1]: registry-server:   retryDelay: 1.1237871116859033
2023-03-21T14:30:04.790830+00:00 app[web.1]: registry-server: }
```

It seems like it's an issue with the credentials, so this task is to update those.

**Comment by wgwz** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/registry-server/305?planning-poker) with Zenhub @blushi

**Comment by wgwz** [comment]
Can be reproduced via:

```
➜  ~ http -f POST https://api-staging.registry.regen.network/files filePath=test.jpg image@/Users/kyle/Desktop/Screen\ Shot\ 2023-03-20\ at\ 4.23.20\ PM.jpg
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 303
Content-Type: application/json; charset=utf-8
Date: Tue, 21 Mar 2023 14:52:01 GMT
Etag: W/"12f-NlML+WrwHnfKXPAsIYD4OZydd6E"
Server: Cowboy
Via: 1.1 vegur
X-Powered-By: Express

{
    "Error": {
        "code": "AccessDenied",
        "extendedRequestId": "MaElKXojM2IW0dsw+db/8x6/NAyCUbJgvZCVOiL6FWURcgUMeDd2ifLNnXz+VdiApBwU8lkMXpc=",
        "message": "Access Denied",
        "region": null,
        "requestId": "9YY1ZBCK4ENPE348",
        "retryDelay": 32.36349601289423,
        "retryable": false,
        "statusCode": 403,
        "time": "2023-03-21T14:52:01.797Z"
    }
}
```

**Comment by wgwz** [comment]
@flagrede i think we're all good with this now, you should be able to use the files endpoint now. LMK if you have any q's.

@blushi i just had to update the policy associated to the registry-server user account in IAM to have the ListBucket permission (not super obvious to figure out, but i think that's all it was)

old policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:CreateBucket",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::regen-registry/projects",
                "arn:aws:s3:::regen-registry/projects/*",
                "arn:aws:s3:::regen-registry/projects/*/*",
                "arn:aws:s3:::regen-registry"
            ]
        }
    ]
}
```

new policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:CreateBucket",
                "s3:DeleteObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::regen-registry/*",
                "arn:aws:s3:::regen-registry"
            ]
        }
    ]
}
```

i also cleaned up the way the resources are specified.

**Comment by wgwz** [comment]
i think we have an issue to work a bit more on in the registry-server related to editing profiles.
i wanted to mention it here because it's this task that got me thinking about it.
the problem is that the `/files` endpoint in the registry server is currently public.

let's assume that we store the profile image in the registry-registry s3 bucket under a folder called `/profiles` and we call the file `<account-id>.jpg`:
- `regen-registry/profiles/<account-id>.jpg`

the trouble is that if an malicious user know the `account-id`, then because the `/files` is not protected with authentication, they could issue a request to update that profile image.
the same would apply for background images too.

luckily, now that we have the authentication system it won't be too hard to create an endpoint that the front-end can make a credentialed request to in order to update their profile/bg image securely.

for now, i think we can proceed with using the `/files` endpoint.
but i guess we should address this pretty soon.

/cc @blushi @flagrede

**Comment by blushi** [comment]
@wgwz agreed thanks for catching that! let's create an issue and tackle this asap.

**Comment by flagrede** [comment]
@wgwz makes sense, thanks for the investigation and explanation! We should make profile editing safer indeed.

**Comment by flagrede** [comment]
@wgwz I made some tests this morning, file upload is working well now !
There's just a small issue left, it seems that image can't be read (getting access denied instead).
Here's an example: https://regen-registry.s3.amazonaws.com/profiles/6f3bdda8-c70e-11ed-ac59-0242ac120002/avatar.jpg

**Comment by blushi** [comment]
@flagrede Public access is disabled on the above resource: https://s3.console.aws.amazon.com/s3/object/regen-registry?region=us-east-1&prefix=profiles%2F6f3bdda8-c70e-11ed-ac59-0242ac120002%2Favatar.jpg&tab=permissions
It seems like the default params for [S3.upload](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) have the ACL set as private: https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl

**Comment by wgwz** [comment]
if you like i can look more into why the ACLs are not working as expected, LMK.

**Comment by blushi** [comment]
Thanks @wgwz, I guess it's fine for now, we can now read images from /profile
But let's definitely tackle the part you mentioned in https://github.com/regen-network/registry-server/issues/305#issuecomment-1481945597 as a separate issue maybe?

**Comment by wgwz** [comment]
Opened the new issue for that separate task:
https://github.com/regen-network/regen-registry/issues/1636
