### ISSUE TITLE
Uploading jpg to /files for profiles fails

### ISSUE THREAD

**Issue by wgwz** [regen-network/registry-server#327]
When testing [the add address to account PR](https://github.com/regen-network/regen-web/pull/1896), I noticed that somehow AWS S3 returns this when a error profile image is a jpg, but if it's jpeg, it's fine. Maybe mimetype issues? 

Here's the cryptic error from AWS in the registry-server.
```
2023-05-10T21:31:40.982001+00:00 app[web.1]: server: s3 Error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
2023-05-10T21:31:40.982037+00:00 app[web.1]: server:     at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:710:35)
2023-05-10T21:31:40.982059+00:00 app[web.1]: server:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
2023-05-10T21:31:40.982076+00:00 app[web.1]: server:     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2023-05-10T21:31:40.982096+00:00 app[web.1]: server:     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)
2023-05-10T21:31:40.982113+00:00 app[web.1]: server:     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
2023-05-10T21:31:40.982132+00:00 app[web.1]: server:     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
2023-05-10T21:31:40.982150+00:00 app[web.1]: server:     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
2023-05-10T21:31:40.982167+00:00 app[web.1]: server:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
2023-05-10T21:31:40.982187+00:00 app[web.1]: server:     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:688:12)
2023-05-10T21:31:40.982204+00:00 app[web.1]: server:     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
2023-05-10T21:31:40.982223+00:00 app[web.1]: server:   code: 'MalformedXML',
2023-05-10T21:31:40.982240+00:00 app[web.1]: server:   region: null,
2023-05-10T21:31:40.982258+00:00 app[web.1]: server:   time: 2023-05-10T21:31:40.979Z,
2023-05-10T21:31:40.982278+00:00 app[web.1]: server:   requestId: 'RFM8WAQ13WTT7Z6W',
2023-05-10T21:31:40.982296+00:00 app[web.1]: server:   extendedRequestId: 'qYNk+Mof15edqupogakiFgNaPNcD0dhLlFrFy8cDZvkYmOsdHBIeC79iLMjXvo871ez8A/X7V+Q=',
2023-05-10T21:31:40.982314+00:00 app[web.1]: server:   cfId: undefined,
2023-05-10T21:31:40.982333+00:00 app[web.1]: server:   statusCode: 400,
2023-05-10T21:31:40.982350+00:00 app[web.1]: server:   retryable: false,
2023-05-10T21:31:40.982369+00:00 app[web.1]: server:   retryDelay: 43.03713501525477
2023-05-10T21:31:40.982386+00:00 app[web.1]: server: }
```

/cc @blushi could you see if you can repro this?

**Comment by wgwz** [comment]
It's possible that the issue is the file size rather than the filetype, there might be a limit to the filesize.

So it may be the same as the issue:

https://github.com/regen-network/regen-registry/issues/1683

**Comment by blushi** [comment]
I could successfully upload a JPG file (relatively light one) so I guess it might be the file size, what was your file size?

**Comment by blushi** [comment]
should this close this in favor of https://github.com/regen-network/regen-registry/issues/1683 ?
we could possibly rename it given your recent findings (eg doesn't seem related to the file size or format, but rather some issue on the client side)

**Comment by wgwz** [comment]
@blushi yeah, that makes sense. i'll close this and also add a note to the other task.
